services:
  steam_parser:
    build: .
    image: ivanpeshykov/steam-parser
    ports:
      - "8001:8001"
    depends_on:
      - telegram_bot

  telegram_bot:
    build: ./telegram-bot
    image: ivanpeshykov/telegram_bot
    ports:
      - "8000:8000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
